### ISSUE TITLE
caravan.spice file used for pre-check is missing top_level connections

### ISSUE THREAD

**Issue by d-m-bailey** [efabless/caravel#105]
The pre-check uses `caravel/spi/lvs/caravan.spice` to check the connections to `user_analog_project_wrapper`.

It is expecting `vccd1_core` to be connected to `user_analog_project_wrapper/vccd1` but the netlist has `mprj/vccd1` connected instead.

All instances in the top level caravan are not connected to any other instances. Maybe the top level wiring was left out or maybe a bad version of magic was used.
Example
```
Xgpio_defaults_block_7 gpio_defaults_block_7/VGND gpio_defaults_block_7/VPWR gpio_defaults_block_7/gpio_defaults[0]
+ gpio_defaults_block_7/gpio_defaults[10] gpio_defaults_block_7/gpio_defaults[11]
```

**Comment by jainsoumil2** [comment]
Will this also error on the precheck on efabless website?

**Comment by carllb** [comment]
It seems that the error is present in both the local mpw-precheck and the efabless website for analog projects.

**Comment by jeffdi** [comment]
Have Risto look at this to see if it is already fixed.

**Comment by azwefabless** [comment]
File must be updated as part of Tapeout. Pins must be added. This particular issue is a subset of the problems we will encounter

**Comment by azwefabless** [comment]
File must be updated as part of Tapeout. Pins must be added. This particular issue is a subset of the problems we will encounter

**Comment by DavidRLindley** [comment]
@d-m-bailey Another for your review.  I can't believe this is still an issue 2+ years after you created it.  Please let me know if I can close this.
